version: '3'

services:
  db:
    container_name: marketplace_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: hedonhermdev
      POSTGRES_USER: userone
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  search:
    container_name: marketplace_search
    image: elasticsearch:6.8.8
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  web:
    container_name: marketplace_web
    build: .
    command: >
      bash -c "python manage.py migrate 
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - search

volumes:
  postgres-data:
  elasticsearch:
