version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: b@bushk@bo!
      MYSQL_DB: marketplace
      MYSQL_USER: userone
      MYSQL_PASSWORD: password999
    ports:
      - "3306:3306"
  search:
    image: elasticsearch:6.8.8
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
  web:
    build: .
    command: >
      bash -c "python manage.py migrate 
      && python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - search
